apiVersion: v1
kind: Service
metadata:
  name: traffic-prediction-service
spec:
  type: NodePort
  selector:
    app: traffic-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
